[package]
name = "pfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfa = "0.10.1"
bio = "1.3.0"
clap = { version = "4.3.4", features = ["derive"] }

