[package]
name = "pfg"
version = "0.1.0"
edition = "2021"

[dependencies]
gfa = "0.10.1"
bio = { git = "https://github.com/andynet/rust-bio", branch = "int_suffix_array" }
clap = { version = "4.3.4", features = ["derive"] }

